version: '3.8'

services:
  backend:
    build: ./backend
    container_name: kahramann/gmail_backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: kahramann/gmail_frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend 