// Modül tanımlamaları
declare module '*.css';
declare module '*.svg';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.mp4';
declare module '*.webm';
declare module './components/Sidebar';
declare module './components/EmailList';
declare module './components/EmailRow'; 